# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0476c3a27306a593353fb8da6ac76f55aeef4ce6c6a034aea558ce599b88a99d29de9ab4904dbf8ac7b57dd0ee29322cee40abc09da3457d62d8183d87123496

test:
  secret_key_base: e937312607dbde3060af328ac82939cb1e0c80b8e89772492cbfb2211c68e6ca6e7a3e700bcecf58fd4046876f5091b7ab90860be26ef19c5e325ca3ea8a3956

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
